app = "iedc-treasure-hunt-backend"
primary_region = "bom"

[build]

[env]
  PORT = "5000"
  DATABASE_URL = "file:./dev.db"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
