services:
  - type: web
    name: iedc-treasure-hunt-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  - type: web
    name: iedc-treasure-hunt-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://iedc-treasure-hunt-backend.onrender.com
      - key: NODE_ENV
        value: production
